
matrix:
  include:
    language: python
    python:
      - "3.6"
    
    - python: 3.7
      dist: xenial
      sudo: true
    script: 
      - echo "Skipping tests until test suite is written."
      
    language: bash
    script: 
      - bash daemon/test.sh
  
