
matrix:
  include:
    #- python: 3.7
    #  dist: xenial
    #  sudo: true
    
    #language: python
    #python:
    #  - "3.6"
    #script: 
    #  - echo "Skipping tests until test suite is written."
      
    language: bash
    before_script:
      - cd daemon/tests
      - python3 --version
    script: 
      - bash daemon/test/test.sh

##Set language to python
#language: python
#
#python:
#  - "3.6"
#  
#matrix:
#  include:
#    - python: 3.7
#      dist: xenial
#      sudo: true
#  
##Command to run tests
#script: 
#  - echo "Skipping tests until test suite is written."
  
  #- pytest  
