matrix:
  include:
    language: python
    python: 3.7
    dist: xenial
    sudo: true
    before_script:
      - echo "Starting before_script"
      - sudo chmod +x ./daemon/test/test.sh
      - sudo pip install GitPython
      - sudo pip install inotify
      - pip list
      - echo "Ending before_script"
    script:
      - ./daemon/test/test.sh
